### ISSUE TITLE
During REDCap bulk import, some records experience connection error

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/utility#18]
```bash
Traceback (most recent call last):
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/predict/utility/import_records.py", line 51, in <module>
    r = requests.post(config['api_url'], data=fields)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/dpimport/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by tashrifbillah** [comment]
This is how we have mostly solved it:
https://github.com/AMP-SCZ/utility/blob/b30cbe9daf4fad5707cffaf59311acafb5ed6b27/import_records_all.py#L5-L32

The rest of the stalemate should be attributed to `/data/predict/`s slow storage.
