### ISSUE TITLE
Mongo timeout on import

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/utility#71]
Mongo timeout on importing large files

```
ERROR:dppylib:SSL handshake failed: rc-predict.partners.org:27017: _ssl.c:980: The handshake operation timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6436c52484f64372f26c0508, topology_type: Single, servers: [<ServerDescription ('rc-predict.partners.org', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('SSL handshake failed: rc-predict.partners.org:27017: _ssl.c:980: The handshake operation timed out')>]>

Traceback (most recent call last):

  File "/data/predict1/miniconda3/bin/import.py", line 4, in <module>

    __import__('pkg_resources').run_script('dpimport==0.0.1', 'import.py')

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script

    self.require(requires)[0].run_script(script_name, ns)

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1479, in run_script

    exec(script_code, namespace, namespace)

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/dpimport-0.0.1-py3.10.egg/EGG-INFO/scripts/import.py", line 191, in <module>

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/dpimport-0.0.1-py3.10.egg/EGG-INFO/scripts/import.py", line 48, in main

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/dpimport-0.0.1-py3.10.egg/dpimport/database/__init__.py", line 69, in exists

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/pymongo-3.11.4-py3.10-linux-x86_64.egg/pymongo/collection.py", line 1319, in find_one

    for result in cursor.limit(-1):

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/pymongo-3.11.4-py3.10-linux-x86_64.egg/pymongo/cursor.py", line 1207, in next

    if len(self.__data) or self._refresh():

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/pymongo-3.11.4-py3.10-linux-x86_64.egg/pymongo/cursor.py", line 1100, in _refresh

    self.__session = self.__collection.database.client._ensure_session()

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/pymongo-3.11.4-py3.10-linux-x86_64.egg/pymongo/mongo_client.py", line 1816, in _ensure_session

    return self.__start_session(True, causal_consistency=False)

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/pymongo-3.11.4-py3.10-linux-x86_64.egg/pymongo/mongo_client.py", line 1766, in __start_session

    server_session = self._get_server_session()

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/pymongo-3.11.4-py3.10-linux-x86_64.egg/pymongo/mongo_client.py", line 1802, in _get_server_session

    return self._topology.get_server_session()

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/pymongo-3.11.4-py3.10-linux-x86_64.egg/pymongo/topology.py", line 496, in get_server_session

    self._select_servers_loop(

  File "/data/predict1/miniconda3/lib/python3.10/site-packages/pymongo-3.11.4-py3.10-linux-x86_64.egg/pymongo/topology.py", line 215, in _select_servers_loop

    raise ServerSelectionTimeoutError(

pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: rc-predict.partners.org:27017: _ssl.c:980: The handshake operation timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 6436c52484f64372f26c0508, topology_type: Single, servers: [<ServerDescription ('rc-predict.partners.org', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('SSL handshake failed: rc-predict.partners.org:27017: _ssl.c:980: The handshake operation timed out')>]>

```

Occurs with dpimport_formqc.sh

Originally reported by @gracejacobs

**Comment by tashrifbillah** [comment]
This line is generating the error:
https://github.com/AMP-SCZ/dpimport/blob/52a0b80e704b20297e2239597d7145db1ae7c7f8/dpimport/database/__init__.py#L69-L72

https://pymongo.readthedocs.io/en/stable/examples/timeouts.html#basic-usage recommends wrapping the above block up with `pymongo.timeoout()`

**Comment by tashrifbillah** [comment]
This two insert blocks may also need to be wrapped by `pymongo.timeout()`:

https://github.com/AMP-SCZ/dpimport/blob/52a0b80e704b20297e2239597d7145db1ae7c7f8/dpimport/importer/__init__.py#L94-L97

**Comment by tashrifbillah** [comment]
Prior to this timeout, there is another error:

```bash
WriteResult({ "nRemoved" : 2 })
Error: error doing query: failed: network error while attempting to run command 'delete' on host 'rc-predict.partners.org:27017'  :
DB.prototype.runCommand@src/mongo/shell/db.js:169:19
DBCollection.prototype._dbCommand@src/mongo/shell/collection.js:176:16
executeBatch@src/mongo/shell/bulk_api.js:912:22
Bulk/this.execute@src/mongo/shell/bulk_api.js:1163:21
DBCollection.prototype.remove@src/mongo/shell/collection.js:414:22
@/data/predict1/utility/remove_assess.js:24:23
@/data/predict1/utility/remove_assess.js:15:5
@/data/predict1/utility/remove_assess.js:12:1
failed to load: /data/predict1/utility/remove_assess.js
exiting with code -3
{"t":{"$date":"2023-05-06T08:33:46.630Z"},"s":"I",  "c":"QUERY",    "id":22791,   "ctx":"js","msg":"Failed to end logical session","attr":{"lsid":{"id":{"$uuid":"182b25d2-4924-4d2a-9ded-1e7489d8962b"}},"error":{"code":9001,"codeName":"SocketException","errmsg":"socket exception [CONNECT_ERROR] server [couldn't connect to server rc-predict.partners.org:27017, connection attempt failed: SocketException: Error connecting to rc-predict.partners.org:27017 (172.31.206.101:27017) :: caused by :: Connection refused]"}}}
```

**Comment by tashrifbillah** [comment]
Solution to https://github.com/AMP-SCZ/utility/issues/71#issuecomment-1537482919:

A few online sources have advised matching server and client's mongo versions. Accordingly, we have updated cluster's (client) mongo version to 4.4.20:

> wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel70-4.4.20.tgz

(There is no mention of this release in https://www.mongodb.com/download-center/community/releases. Tashrif guessed the link from 4.4.21's)

**Comment by tashrifbillah** [comment]
Reference for the above commit:
https://pymongo.readthedocs.io/en/stable/api/pymongo/mongo_client.html

**Comment by tashrifbillah** [comment]
I visually monitored the scenario: I don't think it's any timeout that is severing the connection. At one point of data removal, the server load become 40!!

```bash
(base) [tb571@dn020 utility]$ time mongo --tls --tlsCAFile $state/ssl/ca/cacert.pem \
> --tlsCertificateKeyFile $state/ssl/mongo_client.pem \
> mongodb://dpdash:$MONGO_PASS@$HOST:$PORT/dpdata?authSource=admin \
> --eval "assess=\"form_\"" /data/predict1/utility/remove_assess.js
MongoDB shell version v4.4.6
connecting to: mongodb://rc-predict-dev.partners.org:27017/dpdata?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("c4b4e8c2-6a42-417d-adca-848fbb20f3bf") }
MongoDB server version: 4.4.20
form_
Removing toc
form_digital_biomarkers_mindlamp_onboarding
form_digital_biomarkers_axivity_end_of_12month_study_pe
form_mri_run_sheet
form_cssrs_followup
form_cdss
form_coenrollment_form
form_daily_activity_and_saliva_sample_collection
form_psychosis_polyrisk_score
form_psychs_p1p8_fu_hc
form_psychs_p9ac32_fu_hc
form_screening
form_month7
form_month3
form_month8
form_baseline
form_month1
form_month2
form_month6
form_month5
form_month4
form_conversion
form_traumatic_brain_injury_screen
form_oasis
form_cbc_with_differential
form_gcp_cbc_with_differential
form_gcp_current_health_status
form_speech_sampling_run_sheet
form_assist
form_cssrs_baseline
form_psychosocial_treatment_form
form_inclusionexclusion_criteria_review
form_penncnb
form_digital_biomarkers_axivity_onboarding
form_scid5_psychosis_mood_substance_abuse
form_sociodemographics
form_global_functioning_social_scale_followup
form_global_functioning_role_scale
form_global_functioning_role_scale_followup
form_informed_consent_run_sheet
form_family_interview_for_genetic_studies_figs
form_global_functioning_social_scale
form_current_pharmaceutical_treatment_floating_med_125
form_psychs_p1p8
form_psychs_p9ac32
form_psychs_p1p8_fu
form_psychs_p9ac32_fu
form_premorbid_adjustment_scale
form_health_conditions_genetics_fluid_biomarkers
form_scid5_schizotypal_personality_sciddpq
form_ra_prediction
form_guid_form
form_pgis
form_perceived_discrimination_scale
form_digital_biomarkers_mindlamp_checkin
form_current_health_status
form_digital_biomarkers_axivity_checkin
form_missing_data
form_perceived_stress_scale
form_pubertal_developmental_scale
form_sofas_followup
form_psychs_run_sheet
form_item_promis_for_sleep
form_chart_statuses
form_recruitment_source
form_bprs
form_iq_assessment_wasiii_wiscv_waisiv
form_premorbid_iq_reading_accuracy
form_psychs_av_recording_run_sheet
form_health_conditions_medical_historypsychiatric_histo
form_sofas_screening
form_lifetime_ap_exposure_screen
Error: error doing query: failed: network error while attempting to run command 'delete' on host 'rc-predict-dev.partners.org:27017' 
Error: socket exception [CONNECT_ERROR] server [couldn't connect to server rc-predict-dev.partners.org:27017, connection attempt failed: SocketException: Error connecting to rc-predict-dev.partners.org:27017 (172.31.206.166:27017) :: caused by :: Connection refused]
Error: socket exception [CONNECT_ERROR] server [couldn't connect to server rc-predict-dev.partners.org:27017, connection attempt failed: SocketException: Error connecting to rc-predict-dev.partners.org:27017 (172.31.206.166:27017) :: caused by :: Connection refused]
...
...
runClientFunctionWithRetries@src/mongo/shell/session.js:361:27
runCommand@src/mongo/shell/session.js:455:25
DB.prototype._runCommandImpl@src/mongo/shell/db.js:147:12
DB.prototype.runCommand@src/mongo/shell/db.js:162:16
DBCollection.prototype._dbCommand@src/mongo/shell/collection.js:176:16
executeBatch@src/mongo/shell/bulk_api.js:912:22
Bulk/this.execute@src/mongo/shell/bulk_api.js:1163:21
DBCollection.prototype.remove@src/mongo/shell/collection.js:414:22
@/data/predict1/utility/remove_assess.js:36:9
@/data/predict1/utility/remove_assess.js:15:5
@/data/predict1/utility/remove_assess.js:12:1
failed to load: /data/predict1/utility/remove_assess.js
exiting with code -3
{"t":{"$date":"2023-05-15T21:12:11.480Z"},"s":"I",  "c":"QUERY",    "id":22791,   "ctx":"js","msg":"Failed to end logical session","attr":{"lsid":{"id":{"$uuid":"c4b4e8c2-6a42-417d-adca-848fbb20f3bf"}},"error":{"code":9001,"codeName":"SocketException","errmsg":"socket exception [CONNECT_ERROR] server [couldn't connect to server rc-predict-dev.partners.org:27017, connection attempt failed: SocketException: Error connecting to rc-predict-dev.partners.org:27017 (172.31.206.166:27017) :: caused by :: Connection refused]"}}}

```
