### ISSUE TITLE
Error from _is_file(x, 'surveys', '*Pronet.json')

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/utility#9]
Hi Kevin, please reproduce the error as follows:

```python
source /data/pnl/soft/pnlpipe3/miniconda3/bin/activate && conda activate pnlpipe3
/data/predict/utility/subject_files_status_for_dpdash.py
```

```bash
Finding files status of /data/predict/kcho/flow_test/Pronet/PHOENIX

Traceback (most recent call last):
  File "/data/predict/utility/subject_files_status_for_dpdash.py", line 148, in <module>
    phoenix_files_status(pronet_phoenix_dir, pronet_status_dir)
  File "/data/predict/utility/subject_files_status_for_dpdash.py", line 83, in phoenix_files_status
    df = get_summary_from_phoenix(phoenix_dir)
  File "/data/predict/utility/subject_files_status_for_dpdash.py", line 45, in get_summary_from_phoenix
    lambda x: _is_file(x, 'surveys', '*Pronet.json') or
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/site-packages/pandas/core/series.py", line 3848, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "/data/predict/utility/subject_files_status_for_dpdash.py", line 45, in <lambda>
    lambda x: _is_file(x, 'surveys', '*Pronet.json') or
  File "/data/predict/utility/subject_files_status_for_dpdash.py", line 133, in _is_file
    return _get_file_count(root, subdir, pattern) > 0
  File "/data/predict/utility/subject_files_status_for_dpdash.py", line 128, in _get_file_count
    return len([x for x in list((root / subdir).glob(str)) if x.is_file()])
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/pathlib.py", line 1096, in glob
    drv, root, pattern_parts = self._flavour.parse_parts((pattern,))
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/pathlib.py", line 62, in parse_parts
    drv, root, rel = self.splitroot(part)
  File "/data/pnl/soft/pnlpipe3/miniconda3/envs/pnlpipe3/lib/python3.6/pathlib.py", line 283, in splitroot
    if part and part[0] == sep:
TypeError: 'type' object is not subscriptable

```

**Comment by tashrifbillah** [comment]
Hi Kevin,

https://github.com/AMP-SCZ/utility/commit/c38f8c7c7540d8fefd4cf00a8b2d41fb2dc05155 fixed this error. I do not see any error from 

https://github.com/AMP-SCZ/utility/blob/eda1a6d81e71cd62c271be76a400af543c533ad1/subject_files_status_for_dpdash.py#L37

Were you using a different Python? Reference https://gist.github.com/tashrifbillah/24efeec3219ba3c58c92adc419aac7be?permalink_comment_id=4037001#gistcomment-4037001
